### ISSUE TITLE
Corregir diseño e incluir botones para seleccionar tarjeta

### ISSUE THREAD

**Issue by kholostyak17** [YifanYes/Payment-form#1]
-Hay que englobar todos los inputs dentro de un `<form></form>`
-El botón de submit debe de ser un input de tipo submit en lugar de ser un botón, en este caso los datos del formulario se enviarían cuando el boton fuese presionado.
https://github.com/YifanYes/Payment-form/blob/77a5e122f7fb84284112af9680328b8f187dc25e/index.html#L148

-El diseño del formulario debería ser un poco más parecido al que se os da en el ejercicio.
-Se debería incluir todo el contenido dentro de un contenedor para que no se encuentre expandido en toda la pantalla.
-Hay que incluir botones para seleccionar método de pago

![image](https://user-images.githubusercontent.com/80543950/126610517-1c4ee086-16f1-408a-acd9-ad82d29f20cb.png)

**Comment by YifanYes** [comment]
He corregido los puntos que me has dicho, si puedo mejorar algo más me dices 🙌

**Comment by kholostyak17** [comment]
solucionado!!
